# Generated by Django 4.1.2 on 2022-10-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name="Повне ім'я автора")),
                ('biography', models.TextField(blank=True, verbose_name='Біофграфія про автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва книги')),
                ('language', models.CharField(choices=[('Ukr', 'Українська'), ('Rus', 'Свиняча'), ('Eng', 'Англійська')], default='Ukr', max_length=3, verbose_name='Мова видання')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Зображення')),
                ('content', models.FileField(blank=True, upload_to='content/%Y/%m/%d', verbose_name='Контент')),
                ('authors', models.ManyToManyField(to='books.author', verbose_name='Автори')),
                ('categories', models.ManyToManyField(to='books.category', verbose_name='Категорії')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книга',
                'ordering': ['title', 'price'],
            },
        ),
    ]
