# Generated by Django 4.1.2 on 2022-10-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_test_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'price'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='test_field',
        ),
    ]
