# Generated by Django 4.1.2 on 2022-11-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chunk_title',
            field=models.TextField(blank=True),
        ),
    ]
