# Generated by Django 4.1.2 on 2022-12-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_chunk_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='chunk_title',
            field=models.TextField(blank=True, verbose_name='Розбита назва книги: '),
        ),
    ]
