# Generated by Django 4.1.2 on 2022-12-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_testmodel_alter_book_chunk_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
